### ISSUE TITLE
Incomplete type annotations lead to error diagnostics from static type checkers

### ISSUE THREAD

**Issue by qexat** [Catminusminus/option#2]
First of all, thank you for this library, it is very useful.

Bare `Callable`s are used in some annotations (https://github.com/Catminusminus/option/blob/main/option/option.py#L97-L101) which makes Pyright complain about not knowing the type of `map`, especially for the `Nothing` variant.

I would expect `option` to make the same decision as `result` from which it is inspired, i.e. to annotate it with `object` for the lack of a better solution: https://github.com/rustedpy/result/blob/main/src/result/result.py#L361

**Comment by Catminusminus** [comment]
Hi @qexat.
Thank you for your feedback!
I was a little surprised because I didn't think anyone else was using this library besides myself.

I've created a PR https://github.com/Catminusminus/option/pull/3 that addresses this issue.
Would you review it?

**Comment by qexat** [comment]
Hello, I actually use it quite substantively with its friend `result` :D
I reviewed your PR!

**Comment by Catminusminus** [comment]
Thanks, I'll merge it.
